export const environment = {
  production: false,
  environment: 'This is development environement.',
  baseUrl: 'http://localhost:3000/api/',
  main: '',
  games: 'games',
  profile: 'profile',
  addgame: 'add-game',
  game: 'game/:gameId',
  register: 'register',
  editGame: 'edit-game/:gameId',
  token: 'token',
  data: 'data',
  allFieldsRequired: 'Please fill all the fields!',
  passwordDontMatch: 'Password and confirm doesn\'t match!',
  gotogames: '/games',
  gotoPlatforms: '/platforms',
  platform: 'platform',
  editGameForm: 'editGameForm',
  gameId: 'gameId',
  tableLight: 'table-light',
  tableSecondary: 'table-secondary',
  platformName: 'Platform name',
  releasedYear: 'Released year',
  addPlatform: 'Add platform',
  cancel: 'Cancel',
  addNewPlatform: 'Add New Platform',
  editPlatform: 'Edit Platform',
  edit: 'Edit',
  thousand: 1000,
  exp: 'exp',
  gameTitle: 'Game title',
  publisher: 'Publisher',
  editGameText: 'Edit Game',
  name: 'Name',
  username: 'Username',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  comproLink: 'https://compro.miu.edu',
  footerImage: 'assets/images/compro-web-logo-442x112.webp',
  footerText: 'Maharishi International University. All Rights Reserved.',
  copyRight: '169',
  miuCompro: 'MIU Compro',
  true: true,
  false: false,
  emptyArray: [],
  zero: 0,
  defaultCount: 5,
  addGameText: 'Add Game',
  addNewGame: 'Add New Game',
  myModal: 'my-modal',
  welcome: 'Welcome',
  logOut: 'Log Out',
  logIn: 'Log In',
  videoGameImage: 'assets/images/videogames.jpg',
};
