export const environment = {
  production: false,
  environment: 'This is development environement.',
  baseUrl: 'http://localhost:3000/api/',
  main: '',
  games: 'games',
  profile: 'profile',
  addgame: 'add-game',
  game: 'game/:gameId',
  register: 'register',
  editGame: 'edit-game/:gameId',
  token: 'token',
  data: 'data',
  allFieldsRequired: 'Please fill all the fields!',
  passwordDontMatch: 'Password and confirm doesn\'t match!',
  gotogames: '/games',
  gotoPlatforms: '/platforms',
};
